<template>
  <div class="common">
    <el-table
      :data="queryResult.list"
      border
      size="small"
      style="width: 100%">
      <el-table-column
        type="index"
        label="序号"
        width="50">
      </el-table-column>
      <el-table-column
        prop="genericName"
        label="通用名"
        width="150"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="productName"
        label="商品名"
        width="150"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="productionUnits"
        label="生产单位"
        width="250"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="dosageForm"
        label="剂型"
        width="150"
        :show-overflow-tooltip="true"
      >
        <template slot-scope="scope">
        {{scope.row.dosageForm | dosageForm}}
      </template>
      </el-table-column>
      <el-table-column
        prop="specifications"
        label="规格"
        width="150"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="approvalNumber"
        width="150"
        label="批准文号"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="registrationNumber"
        width="150"
        label="注册证号"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="name"
        width="150"
        label="药品名"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="genericEnglishName"
        label="通用名（英文名）"
        width="150"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="packagingSpecifications"
        width="250"
        label="包装规格"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="packingApprovalNumber"
        width="150"
        label="分包装批准文号"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="basedCode"
        width="150"
        label="药品本位码"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        width="150"
        label="国内外范围"
        :show-overflow-tooltip="true"
      >
        <template slot-scope="scope">
          {{scope.row.atHomeAndAbroad | scope}}
        </template>
      </el-table-column>
      <el-table-column
        prop="classification"
        width="150"
        label="药品种类"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="productCategory"
        width="150"
        label="产品类别"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="treatmentType"
        width="150"
        label="治疗分类"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="countryHealcareDirectory"
        width="150"
        label="纳入国家医保目录"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="countryHealcareDirectoryTime"
        width="150"
        label="纳入国家医保目录时间"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="countryBasicDrugStatus"
        width="150"
        label="是否为国家基本药物"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="countryBasicDrugTime"
        width="150"
        label="纳入国家基本药物时间"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="countryVarietiesNegotialStatus"
        width="150"
        label="是否为国家谈判品牌"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="countryVarietiesNegotialTime"
        width="150"
        label="纳入国家谈判品种时间"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
      <el-table-column
        prop="ypId"
        width="150"
        label="YPID"
        :show-overflow-tooltip="true"
      >
      </el-table-column>
    </el-table>
  </div>
</template>

<script>
  export default {
      props:['queryResult'],

  }
</script>


